### PR TITLE
Implemented chunk based hashing in production

### LINKED ISSUE #11: Long term caching with chunkhash
One feature that would be great to have is long-term caching of chunks by using webpack's `chunkhash` feature. On the browser production build, output files would be renamed to something like `[name].[chunkhash].js`. The consequence is that file names are not predictable anymore so that on the server side render, the webpack stats would need to be read to get the file paths of the javascript files.

### PR DESCRIPTION
**Pull request by jtmthf**
Resolves #11

As of now only implements chunk based hashing for js files. Will look at css and other assets next. Chunk based hashing is only used in production and works with server side rendering and code splitting. Only updated chunks trigger a new chunk hash. For example changing code in the application without updating any dependencies will leave the vendor chunk intact with the same hash.

- [x] chunk based hashing of JavaScript
- [x] chunk based hashing in assets other than JavaScript
- [x] method to clean `dist/public` directory between builds
- [x] set cache policy in koa server

### CODE REVIEW

**Comment by jtmthf** [comment]
I was testing SSR with client-side JavaScript disabled, and noticed that LESS imports were not working. Turned out that the Extract-Text-Plugin wasn't running for LESS so I fixed that in this PR while I was at it.

**Comment by leebenson** [comment]
Thanks @jtmthf. Is this ready for me to merge, or do you want to check off the '_set cache policy in koa server_' first?

**Comment by jtmthf** [comment]
@leebenson I'll quickly throw max-age for one year on the koa-server. Ideally I'd like to set it to immutable, and `koa-send` just so happens to have an open PR for that feature, but looking at the open PR's on both `koa-static` and `koa-send`, it'll probably take a few weeks for that feature to become available. Considering only firefox supports immutable right now, it's good enough for now.

Also I'll get the `yarn.lock` conflict resolved in the next commit as well.

**Comment by jtmthf** [comment]
@leebenson ready to merge now. Caching now reduces second load payload size from 137 KB to 4.2 KB!

**Comment by leebenson** [comment]
thanks for your work on this @jtmthf - great work!

**Comment by leebenson** [comment]
FYI @jtmthf, I fixed an issue in https://github.com/reactql/kit/commit/02b45361a9523b6e47158cf2e60ba9d64dd7254e that prevented chunked assets working on routes like `/page/about`.

I've also moved the assets to `dist` rather than `dist/public` to avoid them being exposed by the web server. Probably not a security concern, more just to clean up the dir.

**Comment by jtmthf** [comment]
@leebenson I think that explains the behavior I saw when refreshing from `/page/about`. I'd say that definitely looks cleaner too.

**Comment by economysizegeek** [comment]
I'm trying to use the npm run build-static- but it is pulling this chunked-manifest.json into the index.html that gets generated. The included bundles then use Webpack JSONP which doesnt' get loaded properly. Am I doing something wrong in the generation process that gives me this stuff insted of just the static files I need for hosting the front end?

**Comment by leebenson** [comment]
@economysizegeek - see https://github.com/reactql/kit/issues/55

**Comment by economysizegeek** [comment]
Awesome! i didn't realize there was another repo to look in or I would have searched more :)

**Pull request merged**
