### PR TITLE
Use minified and optimized React for SSR

### PR DESCRIPTION
**Pull request by jtmthf**
Sasha Aickin has a great [talk](https://www.youtube.com/watch?v=PnpfGy7q96U) where he details steps to improve the performance of SSR React apps. As I was getting ~300ms response times in production. I implemented setting production mode using the Define Plugin, and whitelisted `react` and `react-dom/server` from the externals plugin. I also added a minifier to remove all the dead code from React as well. I couldn't use Uglify because of all the ES2015+ plus syntax on the server so instead I used Babili.

The result was still ~300ms response times. I then realized that the response time from the graphQL server was likely to blame. Turns out the graph.cool server is in Ireland which happens to be pretty far from me. Knowing that ideally the API and page server would be located in the same data-center and the time to fetch data would be minimal, I temporarily commented out `getDataFromTree`. In the original version I was getting around 20 ms for a page response, while with the optimizations I was getting around 10 ms.

At that level the difference is imperceptible, but with a bigger app with more dom nodes, I would expect that this difference would increase as demonstrated in Sasha's talk. The downside to this change here is Babili on the server which is slower than using Uglify, and far slower than using nothing before. On my computer this took the server build from 10s to 25s. As an alternative, the pre-minified version of React and React-DOM can be used instead which is what Sasha did in his demo. I think the best way to do that is using a webpack resolve alias. Another approach to speed up the build would be to use concurrently instead of using webpack's multi compiler mode so that multiple cores can be used. This has the result of bringing the build time back down to where it began.

So first off, I might want to test a DOM node heavy page to see if these changes are still worth it. Also I have doubts on how I changed the server build process. Would using the pre-minified React be a better than this approach? Would it also be worth implementing concurrently in this PR or is that too far out of scope?

### CODE REVIEW

**Comment by leebenson** [comment]
Interesting consideration.

I actually tried Babili before Uglify in a pre-release version, and wound up yanking it out for the same reason - significant build times. Secondary to that was the build size was generally larger than Uglify (only a concern in the browser, of course.)

The 300ms response time was definitely 90-95% comprised of the example graph.cool call. Keeping the `getDataFromTree` call but swapping the `GraphQLMessage` component to this 'plain' version, sans-GraphQL query:

```js
const GraphQLMessage = () => (
  <Message data={{ allMessages: ['Test without GraphQL'] }} />
);
```

... yields consistent response times of **4-15ms** on my local machine with the current Uglify config:

screen shot 2017-04-16 at 11 26 29

Response times circa this range are problematic to gauge-- hitting 'refresh' in the browser can yield 1-4x the original timing, just based on whatever the CPU happens to be doing at the time. Concurrent refreshes about half a second apart yielded 9.209ms, 12.953ms, 4.658ms and 14.273ms... **the highest being 3.06x slower than the fastest.**

Exact same query, no external calls.

So, my feeling at this stage is that enduring an extra 15 second build time is overkill. I like the idea of boosting performance by using a pre-minified build, though - that seems like a freebie without any downside. In the talk you referenced, this code given:

screen shot 2017-04-16 at 11 14 51

Like you said, that'd just be a case of throwing in a resolve alias in Webpack.

What do you think? Want to test the above?

**Comment by leebenson** [comment]
Scratch the Webpack resolve alias, it should actually just be a case of making the switch in `kit/entry/server.js`

**Comment by leebenson** [comment]
I've added the production `process.env.NODE_ENV` var to the [kit repo](https://github.com/reactql/kit), to remove React debugging with the SSR version.

I tried switching `react-dom/server` -> `react/dist/react.min`, but it looks like that's no longer valid because the `renderToString` method is missing. There are a few `dist` versions inside react-dom, but they dump their own errors when trying to use.

@jtmthf, if you want to test/work on this further, please open a PR at the [kit repo](https://github.com/reactql/kit). I'll close this one for now, since the CLI has now been relegated to a pure build tool in [2.2.0](https://github.com/reactql/cli/releases/tag/2.2.0)+

**Comment by jtmthf** [comment]
@leebenson I'll mess around with that and see what comes up

**Pull request closed without merging**
